apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: kv2
  name: kv2
spec:
  replicas: 3
  serviceName: kv2-headless
  selector:
    matchLabels:
      app: kv2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kv2
    spec:
      containers:
      - image: loqutus/kv2:latest-arm64
        name: kv2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      nodeSelector:
        beta.kubernetes.io/arch: arm64
