apiVersion: batch/v1
kind: Job
metadata:
  name: kv2-test
spec:
  template:
    spec:
      containers:
      - name: kv2-test
        image: loqutus/kv2-test:latest-amd64
        imagePullPolicy: Always
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/arch: arm64
  backoffLimit: 0