FROM golang:latest AS build
WORKDIR /go/src/github.com/rusik69/kv2
COPY . ./
RUN make get
RUN make build

FROM alpine:latest
WORKDIR /
COPY --from=build /go/src/github.com/loqutus/kv2/bin/kv2-linux-amd64 /usr/bin/kv2
ENTRYPOINT ["/usr/bin/kv2"]
EXPOSE 6969 6970