on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18.0'
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: make docker_amd64
      run: make docker_amd64
    - name: make docker_arm64
      run: make docker_arm64
    timeout-minutes: 10